var COUNTRYS_DATA = [
"US,United States,美国",
"UK,United Kingdom,英国",
"FR,France,法国",
"IT,Italy,意大利",
"DE,Germany,德国",
"ES,Spain,西班牙",
"NL,Netherlands,荷兰",
"CH,Switzerland,瑞士",
"JP,Japan,日本",
"KR,Korea,韩国",
"BR,Brazil,巴西",
"MX,Mexico,墨西哥",
"AU,Australia,澳大利亚",
"IN,India,印度",
"RU,Russia CIS and Baltics,俄国、独联体及波罗的海国家",
"CA,Canada,加拿大",
"SE,Sweden,瑞典",
"DK,Denmark,丹麦",
"FI,Finland,芬兰",
"IE,Ireland,爱尔兰",
"NO,Norway,挪威",
"NZ,New Zealand,新西兰",
"CN,China Mainland,中国大陆",
"TW,Taiwan,台湾",
"HK,Hong Kong,香港",
"MO,Macao,澳门",
"BE,Belgium,比利时",
"AT,Austria,奥地利",
"CL,Chile,智利",
"CO,Colombia,哥伦比亚",
"CZ,Czech Republic,捷克共和国",
"GR,Greece,希腊",
"HU,Hungary,匈牙利",
"MY,Malaysia,马来西亚",
"PH,Philippines,菲律宾",
"PL,Poland,波兰",
"PT,Portugal,葡萄牙",
"RO,Romania,罗马尼亚",
"SG,Singapore,新加坡",
"TH,Thailand,泰国",
"TR,Turkey,土耳其",
"UA,Ukraine,乌克兰",
"VN,Vietnam,越南",
"ZA,South Africa,南非",
"IL,Israel,以色列",
"DZ,Algeria,阿尔及利亚",
"EG,Egypt,埃及",
"MA,Morocco,摩洛哥",
"OM,Oman,阿曼",
"SA,Saudi Arabia,沙特阿拉伯",
"TN,Tunisia,突尼斯",
"AE,United Arab Emirates,阿拉伯联合酋长国",
"JO,Jordan,约旦",
"LB,Lebanon,黎巴嫩",
"BG,Bulgaria,保加利亚",
"PK,Pakistan,巴基斯坦",
"AR,Argentina,阿根廷",
"PE,Peru,秘鲁",
"VE,Venezuela,委内瑞拉",
"CR,Costa Rica,哥斯达黎加",
"DO,Dominican Republic,多米尼加共和国",
"GT,Guatemala,危地马拉",
"UY,Uruguay,乌拉圭",
"EC,Ecuador,厄瓜多尔",
"BO,Bolivia,玻利维亚",
"PY,Paraguay,巴拉圭",
"PR,Puerto Rico,波多黎各",
"PA,Panama,巴拿马",
"HN,Honduras,洪都拉斯",
"SV,El Salvador,萨尔瓦多",
"HR,Croatia,克罗地亚",
"SI,Slovenia,斯洛文尼亚",
"YU,Serbia,塞尔维亚",
"ID,Indonesia,印度尼西亚",
"IS,Iceland,冰岛",
"LT,Lithuania,立陶宛",
"LV,Latvia,拉脱维亚",
"SK,Slovakia,斯洛伐克",
"AM,Armenia,亚美尼亚",
"AZ,Azerbaijan,阿塞拜疆",
"BY,Belarus,白俄罗斯",
"EE,Estonia,爱沙尼亚",
"KG,Kyrgyzstan,吉尔吉斯斯坦",
"KZ,Kazakhstan,哈萨克斯坦",
"MD,Moldova,摩尔多瓦",
"TJ,Tajikistan,塔吉克斯坦",
"TM,Turkmenistan,土库曼斯坦",
"UZ,Uzbekistan,乌兹别克斯坦",
"AO,Angola,安哥拉",
"BJ,Benin,贝宁",
"BW,Botswana,博茨瓦纳",
"BI,Burundi,布隆迪",
"CF,Central African Republic,中非共和国",
"TD,Chad,乍得",
"CG,Congo,刚果",
"CI,Cote d'Ivoire,科特迪瓦",
"DJ,Djibouti,吉布提",
"CD,DRC,民主刚果",
"ET,Ethiopia,埃塞俄比亚",
"GA,Gabon,加蓬",
"GM,Gambia,冈比亚",
"GH,Ghana,加纳",
"KE,Kenya,肯尼亚",
"LS,Lesotho,莱索托",
"MG,Madagascar,马达加斯加",
"MW,Malawi,马拉维",
"ML,Mali,马里",
"MU,Mauritius,毛里求斯",
"MZ,Mozambique,莫桑比克",
"NA,Namibia,纳米比亚",
"NG,Nigeria,尼日利亚",
"RW,Rwanda,卢旺达",
"ST,Sao Tome and Principe,圣多美和普林西比",
"SN,Senegal,塞内加尔",
"SC,Seychelles,塞舌尔",
"SL,Sierra Leone,塞拉利昂",
"TZ,Tanzania,坦桑尼亚",
"TG,Togo,多哥",
"UG,Uganda,乌干达",
"ZM,Zambia,赞比亚",
"ZW,Zimbabwe,津巴布韦",
"BF,Burkina Faso,布基纳法索",
"CM,Cameroon,喀麦隆"
];




var US_CITYS = {code: "US",cities: [{name:"Albany"},{name:"Atlanta"},{name:"Annapolis"},{name:"Baltimore"},{name:"Birmingham"},{name:"Buffalo"},{name:"CHICAGO"},{name:"Cincinnati"},{name:"Cleveland"},{name:"Columbus"},{name:"Dallas"},{name:"Denver"},{name:"Fairbanks"},{name:"Philidelphia"},{name:"Honolulu"},{name:"Indianapolis"},{name:"Jacksonville"},{name:"Kansas City"},{name:"Los Angeles"},{name:"Las Vegas"},{name:"Minneapolis"},{name:"New York"},{name:"New Orleaans"},{name:"Albany"},{name:"Omaha"},{name:"Phoenix"},{name:"Pittsburgh"},{name:"Salt Lake City"},{name:"Sacramento"},{name:"San Diego"},{name:"San Francisco"},{name:"San Jose"},{name:"Saint Paul"},{name:"Saint Louis"},{name:"Seattle"},{name:"Tampa"}]}

	